language: java
jdk:
 - oraclejdk8

git:
  depth: 42000

before_script:
  - sudo service postgresql stop || true
  - sudo service mysql stop || true
  - sudo service memcached stop || true
  - sudo service bootlogd stop || true
  - sudo service elasticsearch stop || true
  - sudo service mongodb stop || true
  - sudo service neo4j stop || true
  - sudo service cassandra stop || true
  - sudo service rsync stop || true
  - sudo service x11-common stop || true
  - unzip -P $SIGNITURE_PASSWORD signiture.zip
before_install:
 - "export DISPLAY=:99.0"
 - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -extension RANDR -screen 0 1280x1024x16"
 - chmod +x gradlew

addons:
  coverity_scan:
    project:
      name: "fujaba/SDMLib"
      description: "Build submitted via Travis CI"
    notification_email: Stefan.Lindel@cs.uni-kassel.de
    build_command_prepend: "gradle clean"
    build_command:   "gradle -xTest -xJavadoc"
    branch_pattern: coverity_scan
after_success: 
  - ./gradlew version build uploadArchives
